### ISSUE TITLE
Your File System

### ISSUE THREAD

**Issue by KaiH-0** [matthew-nagy/Packed-Filesystem#1]
Hi,

I found your filesystem by searching on GitHub as I needed a virtual filesystem that was just one file so this was perfect for me but I'm not quite sure how I would pack my own files into it and then read them in memory.

If you can help, it would be much appreciated!

**Comment by matthew-nagy** [comment]
Hello!

Unfortunately I don't think I ever got around to finishing this project, and there are some quite nasty resource leaks you get when you delete things from the file structure, so I wouldn't recommend using this.

I had sort of forgotten that this was public until I saw this message, and will probably private it in the near future. If you are looking for such a filesystem, making one yourself with a serialization tool like https://uscilab.github.io/cereal/ to serialize any vectors or maps you would need may not be too painful?

Sorry that I couldn't help more
